I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 288, in script
    python:
ScriptError: could not find label 'start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Volumes/renpy-8.3.3-sdk 1/renpy-8.3.3-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Volumes/renpy-8.3.3-sdk 1/renpy-8.3.3-sdk/renpy/main.py", line 652, in main
    run(restart)
  File "/Volumes/renpy-8.3.3-sdk 1/renpy-8.3.3-sdk/renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "/Volumes/renpy-8.3.3-sdk 1/renpy-8.3.3-sdk/renpy/execution.py", line 958, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 288, in script
    python:
  File "/Volumes/renpy-8.3.3-sdk 1/renpy-8.3.3-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'start'.

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
 
Wed Jan 29 12:36:25 2025
