I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 967, in script
    show elliot default right
Exception: Image 'elliot default' does not accept attributes 'right'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 967, in script
    show elliot default right
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/exports/displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/display/displayable.py", line 249, in _duplicate
    args.extraneous()
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/display/displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'elliot default' does not accept attributes 'right'.

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
3 More Days 1.0
Wed Mar 12 03:29:39 2025
