I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script1.rpy", line 1211, in script
    $ time_travel_jump("E1")
  File "game/script1.rpy", line 1211, in <module>
    $ time_travel_jump("E1")
  File "game/01cds.rpy", line 30, in time_travel_jump
    renpy.sound.play("audio/time travel/whoosh.mp3", renpy.volume("0.25"), channel="sound")
AttributeError: module 'renpy.exports' has no attribute 'volume'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script1.rpy", line 1211, in script
    $ time_travel_jump("E1")
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script1.rpy", line 1211, in <module>
    $ time_travel_jump("E1")
  File "game/01cds.rpy", line 30, in time_travel_jump
    renpy.sound.play("audio/time travel/whoosh.mp3", renpy.volume("0.25"), channel="sound")
AttributeError: module 'renpy.exports' has no attribute 'volume'

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
3 More Days 1.1
Wed Apr 30 00:46:03 2025
