I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00keymap.rpy", line 504, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 504, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 528, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jayokuo/Library/RenPy/3MoreDays-1731805578/_reload-1-LT1.save'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00keymap.rpy", line 504, in script
    python hide:
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 504, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 528, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/loadsave.py", line 460, in save
    location.save(slotname, sr)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/savelocation.py", line 517, in save
    l.save(slotname, record)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/savelocation.py", line 211, in save
    record.write_file(filename)
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/loadsave.py", line 350, in write_file
    raise e
  File "/Users/jayokuo/Desktop/renpy-8.3.3-sdk/renpy/loadsave.py", line 347, in write_file
    shutil.copyfile(self.first_filename, filename_new)
  File "lib/python3.9/shutil.py", line 264, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jayokuo/Library/RenPy/3MoreDays-1731805578/_reload-1-LT1.save'

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
3 More Days 1.2
Thu Jun  5 22:08:44 2025
